### ISSUE TITLE
How do we get the 4 polarized images (0, 45, 90, 135) from the dataset?

### ISSUE THREAD

**Issue by mingyangx** [ChenyangLEI/CVPR2020-Polarized-Reflection-Removal-with-Perfect-Alignment#3]
Thanks for this impressive work! 

The shared dataset only contains single channel grayscale images. How should I get the corresponding 4 polarized images? Thanks!

**Comment by ChenyangLEI** [comment]
try to use [::2,::2], [1::2,::2], ... to get the 4 images.

Basically, 4 polarization pixels is organized to a 2x2 pixel unit.

**Comment by ChenyangLEI** [comment]
Check this for further understanding.

http://image-sensors-world.blogspot.com/2018/02/sony-enters-polarization-sensitive.html

**Comment by mingyangx** [comment]
Thanks you very much!
